@startuml
'https://plantuml.com/use-case-diagram

:管理员: as Admin
:会员: as User


User -> (购买信息客户维护)
(购买信息客户维护) .. (订单维护项)
(订单维护项) .. (订单修改)
(订单维护项) .. (订单删除)
(购买信息客户维护) .. (维护订单)
(维护订单) .. (最新订单查询)

Admin -> (购买信息管理员维护)
(购买信息管理员维护) .. (购买信息查询)
(购买信息管理员维护) .. (资料修改)
(购买信息管理员维护) .. (资料删除)
(购买信息查询) .. (导出信息)
(购买信息查询) .. (订单信息)
(购买信息查询) .. (订单项信息)
(购买信息查询) .. (注册用户信息)

(购买信息客户维护) -> (购买信息维护)
(购买信息管理员维护) -> (购买信息维护)
@enduml
