@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "浏览器" as Client #99FF99
participant "接口服务器" as Server
== 检索 ==
Client -> Server: 查询列表初始化数据
Server -> Client:返回：列配置、检索配置、列描述
Client -> Client:列表界面初始化
Client -> Server: 查询数据：列信息、检索条件
Server -> Client:返回：列表数据
Client -> Client:渲染列表数据
== 用户偏好配置 ==
Client -> Server: 保存列配置
Client -> Server: 保存检索配置
Client -> Server: .....
@enduml
