@startuml
'https://plantuml.com/sequence-diagram

autonumber
box "用户域" #LightBlue
participant "RCP" as Client #99FF99
participant "代理服务器" as PServer
participant "零信任服务器" as 0Server
end box
box "防火墙" #99FF99
participant "可信接入检控" as FireWall
end box
box "数据域" #LightBlue
participant "WS服务器" as WSServer #orange
end box
== 登录 ==
Client -> PServer: 登录请求
PServer <-> 0Server: 接口认证
PServer -> PServer: 缓存令牌
PServer -> FireWall: 携带令牌转发
FireWall -> FireWall: 访问控制
FireWall -> WSServer: 转发
WSServer -> WSServer: 业务处理
WSServer -> Client: 返回
== 业务操作 ==
Client -> PServer: 其他请求
PServer -> PServer: 获取令牌
PServer -> FireWall: 携带令牌转发
FireWall -> FireWall: 访问控制
FireWall -> WSServer: 转发
WSServer -> WSServer: 业务处理
WSServer -> Client: 返回
@enduml
