@startuml
'https://plantuml.com/sequence-diagram
autonumber
participant "数据库" as db
box "查询服务" #AliceBlue
participant "同步程序" as service #orange
participant "搜索引擎" as search
end box
db -> service :查询视图
service -> search :创建索引
service -> service:记录同步时间
@enduml
