@startuml
node 浏览器 {

}
database 智鉴Oracle {

}
database 数据汇聚Oracle {

}

database 证照库Oracle {

}
node 智鉴Jboss {

}
node SumeJboss {

}


frame 实战应用平台 {
  node 前端页面服务器
  node 接口服务器
}

浏览器 -[bold]> 前端页面服务器 : http
前端页面服务器 -[bold]> 接口服务器 : http
接口服务器 -[bold]> SumeJboss : ejb
接口服务器 --[bold]> 数据汇聚Oracle : jdbc-统计
接口服务器 --[bold]> 智鉴Oracle : jdbc-统计
接口服务器 --[bold]> 证照库Oracle : jdbc-统计
接口服务器 --[bold]> 智鉴Jboss : ejb
@enduml
